<main>
  <h1>Projects</h1>
    <article>
      <a href='hkweather.html'><h3>Hello Kitty Weather App</h3></a>
    </article>
                
    <article>
      <h3>ActionScript Calculator</h3>
    </article>
                
    <article>
      <h3>Workout With Me App</h3>
    </article>
                
    <article>
      <h3>Full Sail Advertisement</h3>
    </article>
                
    <article>
      <h3>Cooking School Website Redesign</h3>
    </article>
                
    <article>
      <h3>Audio App</h3>
    </article>
                
    <article>
      <h3>Picture Viewer</h3>
    </article>
                
    <article>
      <h3>Mac Make-up Lovers Website</h3>
    </article>
                
    <article>
      <h3>Be Beautiful Salon Website</h3>
    </article>
                
    <article>
      <h3>Vacation Commercial</h3>
    </article>
              
  </main>
  