<main>
  <h1>Projects</h1>
    <article>
      <a href=?action=hkweather><h3>Hello Kitty Weather App</h3></a>
    </article>
                
    <article>
      <a href=?action=ascalculator><h3>ActionScript Calculator</h3></a>
    </article>
                
    <article>
      <a href=?action=wowm><h3>Workout With Me App</h3></a>
    </article>
                
    <article>
      <a href=?action=fsadv><h3>Full Sail Advertisement</h3></a>
    </article>
                
    <article>
      <a href=?action=cswebsite><h3>Cooking School Website Redesign</h3></a>
    </article>
                
    <article>
      <a href=?action=audioapp><h3>Audio App</h3></a>
    </article>
                
    <article>
      <a href=?action=picviewer><h3>Picture Viewer</h3></a>
    </article>
                
    <article>
      <a href=?action=macwebsite><h3>Mac Make-up Lovers Website</h3></a>
    </article>
                
    <article>
      <a href=?action=bbswebsite><h3>Be Beautiful Salon Website</h3></a>
    </article>
                
    <article>
      <a href=?action=vacationcomm><h3>Vacation Commercial</h3></a>
    </article>
              
  </main>
  